spring:
  config:
    import: optional:configserver:http://config-server-0.config-server.default.svc.cluster.local:8888
  application:
    name: discovery

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka