apiVersion: apps/v1
kind: Deployment
metadata:
  name: clubs
  labels:
    app: clubs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clubs
  template:
    metadata:
      labels:
        app: clubs
    spec:
      containers:
      - name: clubs
        image: capitale48/clubs-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8020

---

apiVersion: v1
kind: Service
metadata:
  name: clubs-svc
spec:
  selector:
    app: clubs
  ports:
  - port: 80
    targetPort: 8020