apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: capitale48/employees-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8050

---

apiVersion: v1
kind: Service
metadata:
  name: employees-svc
spec:
  selector:
    app: employees
  ports:
  - port: 80
    targetPort: 8050