apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: capitale48/gateway-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8222

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 8222
    protocol: TCP