apiVersion: apps/v1
kind: Deployment
metadata:
  name: parents
  labels:
    app: parents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parents
  template:
    metadata:
      labels:
        app: parents
    spec:
      containers:
      - name: parents
        image: capitale48/parents-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8070

---

apiVersion: v1
kind: Service
metadata:
  name: parents-svc
spec:
  selector:
    app: parents
  ports:
  - port: 80
    targetPort: 8070