apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
  labels:
    app: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student
        image: capitale48/student-service
        imagePullPolicy: Always
        env:
        - name: CONFIG_SERVER_ADDRESS
          value: "http://config-server-svc:80"
        - name: DATABASE_ADDRESS
          value: "database-svc:80"
        - name: KAFKA_ADDRESS
          value: "crs-kafka-0.kafka-cluster.default.svc.cluster.local:9092"
        ports:
        - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: student-svc
spec:
  selector:
    app: student
  ports:
  - port: 80
    targetPort: 8090