apiVersion: apps/v1
kind: Deployment
metadata:
  name: towns
  labels:
    app: towns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: towns
  template:
    metadata:
      labels:
        app: towns
    spec:
      containers:
      - name: towns
        image: capitale48/towns-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8060

---

apiVersion: v1
kind: Service
metadata:
  name: towns-svc
spec:
  selector:
    app: towns
  ports:
  - port: 80
    targetPort: 8060