apiVersion: apps/v1
kind: Deployment
metadata:
  name: view
  labels:
    app: view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view
  template:
    metadata:
      labels:
        app: view
    spec:
      containers:
      - name: view
        image: capitale48/view-service
        imagePullPolicy: Always
        env:
        - name: KAFKA_ADDRESS
          value: "crs-kafka-0.kafka-cluster.default.svc.cluster.local:9092"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: view-svc
spec:
  selector:
    app: view
  ports:
  - port: 80
    targetPort: 8000