server:
  port: 8010
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: apiexterna


application:
  config:
    parents-url: http://localhost:8070/api/v1/parents
    towns-url: http://localhost:8060/api/v1/towns

management:
  tracing:
    sampling:
      probability: 1.0