server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    hostname: discovery
    preferIpAddress: false

spring:
  application:
    name: discovery
