server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: students
          predicates:
            - Path=/api/v1/students/**
          uri: lb://students
        - id: parents
          predicates:
            - Path=/api/v1/parents/**
          uri: lb://parents
        - id: towns
          predicates:
            - Path=/api/v1/towns/**
          uri: lb://towns
        - id: employees
          predicates:
            - Path=/api/v1/employees/**
          uri: lb://employees
        - id: marks
          predicates:
            - Path=/api/v1/marks/**
          uri: lb://marks
        - id: teachers
          predicates:
            - Path=/api/v1/teachers/**
          uri: lb://teachers
        - id: clubs
          predicates:
            - Path=/api/v1/clubs/**
          uri: lb://clubs
        - id: apiexterna
          predicates:
            - Path=/api/v1/apiexterna/**
          uri: lb://apiexterna
        - id: view
          predicates:
            - Path=/api/v1/view/**
          uri: lb://view
