server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: students
          predicates:
            - Path=/api/v1/students/**
          uri: http://localhost:8090
        - id: parents
          predicates:
            - Path=/api/v1/parents/**
          uri: http://localhost:8070
        - id: towns
          predicates:
            - Path=/api/v1/towns/**
          uri: http://localhost:8060
        - id: employees
          predicates:
            - Path=/api/v1/employees/**
          uri: http://localhost:8050
        - id: marks
          predicates:
            - Path=/api/v1/marks/**
          uri: http://localhost:8040
        - id: teachers
          predicates:
            - Path=/api/v1/teachers/**
          uri: http://localhost:8030
        - id: clubs
          predicates:
            - Path=/api/v1/clubs/**
          uri: http://localhost:8020
        - id: apiexterna
          predicates:
            - Path=/api/v1/apiexterna/**
          uri: http://localhost:8010
        - id: view
          predicates:
            - Path=/api/v1/view/**
          uri: http://localhost:8000

management:
  tracing:
    sampling:
      probability: 1.0