server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: parents
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-svc:80/parents
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect