server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
application:
  config:
    parents-url: http://parents/api/v1/parents
    towns-url: http://towns/api/v1/towns
    clubs-url: http://clubs/api/v1/clubs
    view-url: http://view/api/v1/view


management:
  tracing:
    sampling:
      probability: 1.0

