server:
  port: 8090
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    parents-url: http://localhost:8070/api/v1/parents
    towns-url: http://localhost:8060/api/v1/towns
    clubs-url: http://localhost:8020/api/v1/clubs

management:
  tracing:
    sampling:
      probability: 1.0