server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: teachers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-svc:80/teachers
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    parents-url: http://parents/api/v1/parents
    towns-url: http://towns/api/v1/towns
    clubs-url: http://clubs/api/v1/clubs