version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: students
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
